---
title: "Reprodukovatelna analyza s R packages"
author: "Jan Schubert"
date: "May 19, 2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## O cem to dnes bude

O cem to dnes bude:

* Jak usetrit cas a 
* Zlepsit kvalitu

<br></br>
Pro koho:

* Sdilite kod/report s kolegy

* Pisete pravidelny report


## Error!

Jeden dlouhy soubor s kodem neni tvuj kamarad:

* Udrzba takoveho kodu je narocna
* Najit, kde je chyba je trva spoustu casu
* Vetsinou je kod spatne dokumentovany
* Zavislosti mezi packages nejsou vyreseny


## Od kodu k R package
**R kod**

* Stejny kod vice nez 3x udelejte funckci

<br></br>
**R Markdown**

* Vice nez 3x funkce udelejte package

<br></br>
**R Package**


## Proc packages

Diky standardum, kterou packages ocekavani musite:

* vytvorit funkce, ktere jsou jedodussi na udrzbu na debugging
* Popsat vsechny argumenty funkce, vystupy a vytvorit priklady/testy funkci
* Pokud pouzivate data musite popsat zdroj a jednotlive promenne 


## ```devtools``` je tvuj kamarad

Pokud jste nikdy R package nedelali, je to jednodussi nez se zda.


## Proc Package #1 - dokumentace funkci
S ```roxygen2``` je vytvoreni dokumentace hracka

Z kodu:
```
#' Same As Above
#'
#' Replaces empty rows by the value above
#' @param x a vector of length > 2
#' @keywords replace
#' @export
#' @examples
#' sameasabove(c(2,1,3,"","",4,NA))
```

Bude vytvorena dokumentace:
```
?sameasabove
```

## Proc Package #2 - dokumentace dat {.smaller}

```
#' Categorized climbs from giro 2019
#'
#' A dataset containing categorized climbs from giro 2019.
#'
#' @format A data frame with 39 rows and 14 variables:
#' \describe{
#'   \item{tappa}{stage, number}
#'   \item{partenza}{start town, factor}
#'   \item{arrivo}{arrival town, factor}
#'   \item{gpm}{name of the climb, factor}
#'   \item{cat}{category climb, factor}
#'   \item{quota(m)}{altitude at the top of a climb, number}
#'   \item{distgpm}{distance from finish at the top of a climb, number}
#'   \item{iniziosalita}{start town of a climb, factor}
#'   \item{quota(m)}{altitude start of a climb, number}
#'   \item{dist.(km)}{start climb distance from finish, number}
#'   \item{lungh.(km)}{length of a climb, number}
#'   \item{disl.(m)}{elevation difference, number}
#'   \item{p.med}{average gradient, number}
#'   \item{p.max}{max gradient, number}
#' }
#' @source \url{http://www.giroditalia.it/wp-content/uploads/2019/04/Garibaldi_Giro_italia_2019_low_res.pdf}
"climbs"
```


## Proc Package #3 - debugging
Pokud spravne definujete ocekavane hodnoty vasich argumentu ve funkci, nemusite travit cas hledanim problemu a muzete zacit rovnou napravovat 
```
sameasabove <- function(x) {
  if(length(x) != 2) stop("x must be of length 2")

  for(i in 2:length(x)) {
    if(is.null(x[i]) | is.na(x[i]) | x[i] == "") x[i] <- x[i-1]
  }
  return(x)
}
```

## Proc Package #4 - zavislosti mezi packages
```roxygen2``` se postara o instalaci vsech packages potrebnych pro zopakovani vasi analyzy. 

```
# Generated by roxygen2: do not edit by hand

export(createhilldata)
export(hillplot)
export(sameasabove)
export(stage.scrape)
importFrom(graphics,plot)
importFrom(rvest,html_node)
importFrom(rvest,html_table)
importFrom(xml2,read_html)
```

## Proc Package #5 - vytvoreni reportu a sdileni
```devtools::use_vignette()``` will create a tempated RMarkdown in folder vignettes.


```devtools::build_vignettes()``` generates a html document in inst/docs

Pokud pouzivate Github celou analyzu je mozne stahnout pomoci ```devtools::install_github()``` nebo  muzete sdilet html report jednodusse na Github pages
